#!/usr/bin/env python3
"""Generate tiered, motor-difficulty-filtered word lists from wordfreq.

Tiers by conversational frequency rank: T1 = 1-1000, T2 = 1001-2000, T3 = 2001-3000.
Within each category, words stay in frequency order (most common first) so the
app can introduce new words by popularity.

Run: python3 scripts/build_words.py   → writes src/words.gen.js + prints stats
"""
import json
import re
from wordfreq import top_n_list, word_frequency, zipf_frequency

TOP_N = 3000
TIERS = [(0, 1000), (1000, 2000), (2000, 3000)]

# words the letter-pattern filters catch but that are NOT motor-difficult
# (silent letters or trivially easy pronunciations)
STOP = {
    "could", "would", "should", "walk", "talk", "talked", "talking", "walking",
    "folk", "folks", "chalk", "yolk", "half", "who", "whose", "whom", "whole",
    "answer", "island", "listen", "often", "castle", "christmas", "wednesday",
    "climbed", "comb", "thumb", "dumb", "lamb", "limb", "debt", "doubt",
    "receipt", "iron", "colonel", "sword", "know", "known", "knows", "knew",
}

# ending patterns that look like clusters but are single sounds / silent
FC_EXCLUDE_END = re.compile(r"(gh|ght|ng|ck|ss|ll|ff|zz|mb|gn|wn|sh|ch|tch|dge|ce|ge|se|ze|ve|le|re|ue|ye|oe)$")
VOWEL_TH_END = re.compile(r"[aeiou]th$")  # plain final th = th category, not a cluster

CATS = {
    "th":  lambda w: "th" in w,
    "tri": lambda w: re.search(r"(str|spr|scr|spl|squ|thr)", w) is not None,
    "lb":  lambda w: re.search(r"(bl|cl|fl|gl|pl|sl)", w) is not None
                     and re.search(r"(b|p|c|g|f|d|t|s)les?$", w) is None,   # table/people = syllabic l, not a blend
    "rb":  lambda w: re.search(r"(br|cr|dr|fr|gr|pr|tr)", w) is not None,
    "sb":  lambda w: re.match(r"s(t|p|c|k|m|n|w)", w) is not None,
    "fc":  lambda w: re.search(r"[bcdfgklmnprstvz]{2}$", w) is not None
                     and FC_EXCLUDE_END.search(w) is None
                     and VOWEL_TH_END.search(w) is None,
}

words = [w for w in top_n_list("en", TOP_N * 2)
         if w.isalpha() and len(w) >= 3 and w not in STOP][:TOP_N]

tiers_out = {c: [[], [], []] for c in CATS}
for rank, w in enumerate(words):
    tier = next(i for i, (lo, hi) in enumerate(TIERS) if lo <= rank < hi)
    for cat, test in CATS.items():
        if test(w):
            tiers_out[cat][tier].append(w)

# ---- stats ----
def cov(lo, hi):
    return sum(word_frequency(w, "en") for w in words[lo:hi])

print("token coverage of English (wordfreq, all top-N words incl. easy ones):")
for i, (lo, hi) in enumerate(TIERS):
    print(f"  tier {i+1} (rank {lo+1}-{hi}): {cov(lo, hi)*100:.1f}%")
print(f"  'the' alone: {word_frequency('the','en')*100:.2f}%")
for r in (0, 99, 999, 1999, 2999):
    w = words[r]
    print(f"  rank {r+1}: '{w}'  freq {word_frequency(w,'en')*100:.4f}%  zipf {zipf_frequency(w,'en')}")

total = 0
print("\ncategory counts (t1/t2/t3):")
for cat, ts in tiers_out.items():
    n = sum(len(t) for t in ts)
    total += n
    print(f"  {cat}: {len(ts[0])}/{len(ts[1])}/{len(ts[2])}  = {n}")
print(f"  total (with cross-category overlap): {total}")
uniq = len({w for ts in tiers_out.values() for t in ts for w in t})
print(f"  unique words: {uniq}")

with open("src/words.gen.js", "w") as f:
    f.write("// GENERATED by scripts/build_words.py — do not edit by hand.\n")
    f.write("// [tier1, tier2, tier3] per category; each tier in frequency order.\n")
    f.write("export const WORD_TIERS = ")
    f.write(json.dumps(tiers_out, separators=(",", ":")))
    f.write(";\n")
print("\nwrote src/words.gen.js")
