#!/usr/bin/env node
// Tag every sentence in the app with its §6 ladder data: target word, the
// target's sound category, and how many instances of that sound the sentence
// carries (function words never count). 1 instance → set 1, 2 → set 2,
// 3+ → set 3. Stored in the data file (src/sentences.gen.js), not computed at
// runtime, so the ladder can be recomposed later (§6A user-adjustable
// difficulty). Appends a bucket-inventory audit to vocab-audit.md.
//   node scripts/tag_sentences.mjs   (run AFTER build_words.py)
import { writeFileSync, appendFileSync } from "fs";

const { SENTENCES, SCENARIO_SENTENCES, SCENARIOS, FUNCTIONAL, topTarget, ladderTarget, catOf, sentenceInstances } =
  await import("../src/data.js");

const meta = {};
const tag = (s) => {
  const w = ladderTarget(s);
  if (!w) { meta[s] = { w: topTarget(s), cat: null, n: 0 }; return; }
  const cat = catOf(w);
  meta[s] = { w, cat, n: sentenceInstances(s, cat) };
};
Object.values(SENTENCES).flat().forEach(tag);
Object.values(SCENARIO_SENTENCES).flat().forEach(tag);
FUNCTIONAL.forEach(tag);

let js = "// GENERATED by scripts/tag_sentences.mjs — do not edit by hand.\n";
js += "// { w: target word, cat: its sound category, n: instances of that sound }\n";
js += "// n drives the §6 ladder: 1 → set 1, 2 → set 2, 3+ → set 3.\n";
js += "export const SENT_META = " + JSON.stringify(meta) + ";\n";
writeFileSync("src/sentences.gen.js", js);

// --- audit: can each bank fill a 10-couple set per ladder rung? ------------
const bucket = (list) => {
  const b = { 1: 0, 2: 0, 3: 0, none: 0 };
  for (const s of list) {
    const { n, cat } = meta[s];
    if (!cat || n === 0) b.none++;
    else if (n === 1) b[1]++;
    else if (n === 2) b[2]++;
    else b[3]++;
  }
  return b;
};
const rows = [];
const scenName = Object.fromEntries(SCENARIOS.map((s) => [s.id, s.name]));
const practiceBank = [...Object.values(SCENARIO_SENTENCES).flat(), ...Object.values(SENTENCES).flat()];
rows.push(["Practice (all banks)", practiceBank]);
for (const [id, list] of Object.entries(SCENARIO_SENTENCES)) rows.push([scenName[id] || id, list]);

let audit = "\n## Sentence ladder inventory (§6) — instances of the target sound per sentence\n\n";
audit += "A couples set needs 10 sentences. Set 1 uses exactly-1-instance sentences, set 2 exactly 2, set 3 uses 3+. ";
audit += "Where a rung has fewer than 10, the app falls back to the nearest rung rather than inventing sentences — flagged below.\n\n";
audit += "| Bank | 1 instance (set 1) | 2 instances (set 2) | 3+ (set 3) | no target sound | flags |\n|---|---|---|---|---|---|\n";
const flagged = [];
for (const [name, list] of rows) {
  const b = bucket(list);
  const flags = [];
  for (const rung of [1, 2, 3]) if (b[rung] < 10) flags.push(`set ${rung} rung thin (${b[rung]})`);
  if (flags.length) flagged.push(name);
  audit += `| ${name} | ${b[1]} | ${b[2]} | ${b[3]} | ${b.none} | ${flags.join("; ")} |\n`;
}
appendFileSync("vocab-audit.md", audit);
console.log(`tagged ${Object.keys(meta).length} sentences -> src/sentences.gen.js`);
for (const [name, list] of rows) console.log(name, bucket(list));
if (flagged.length) console.log("THIN RUNGS:", flagged.join(", "));
